# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de4871a87ba83f681d668086829adea76300a7f93eb024460a5f1addb09431981c1b9bb1b48fca09880d6cafdfb60565427f95faa95bbea78ad7ed303c59fcf3

test:
  secret_key_base: 584546d6c2dfc0b406f002c37d40f90d9faf7547985d00eb4ca89c021c2f1d9b08e5adc85fe596a2333ea0c614df62df2a411304539e44867caa513744de1409

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
